name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 90
          days-before-issue-close: 60
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 90 days with no activity."
          close-issue-message: "This issue is closed because it has been inactive for 60 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          
